import React from "react";
import { Heart, Sun, Cog } from "lucide-react";
import { Divider } from "@mui/material";
import { useMediaQuery } from "@mui/material";

const HowItWorks = () => {
  const isDesktop = useMediaQuery("(min-width:768px)");

  const features = [
    {
      icon: <Heart className="w-6 h-6" />,
      title: "Create Agents",
      description:
        "Launch your AI agents on our platform using the AI engines above or use any engine of your choice. Each agent starts in the matrix, waiting to be awakened.",
    },
    {
      icon: <Sun className="w-6 h-6" />,
      title: "Own / Hire the Agents",
      description:
        "Users can buy tokens on the bonding curve to become part owners of the AI Agent and get rewarded for being loyal owners of the AI Agents. These ready to use AI Agents can be hired for a fee from the marketplace by Users / Businesses to help solve real use cases.",
    },
    {
      icon: <Cog className="w-6 h-6" />,
      title: "Revenue Share",
      description:
        "The revenue generated by the AI Agents is distributed back to the owners of the agent through buyback of the Agent token and given to the larger community to build a thriving Agent Nation.",
    },
  ];

  return (
    <div
      className="relative py-6 rounded-md"
      style={{
        background:
          "url(/images/aiEngineBg.png), linear-gradient(180deg, #0CDCF4 0%, #C2C7FF 100%)",
        backgroundBlendMode: "overlay",
        borderRadius: "32px",
        flex: 1,
        margin: `${isDesktop ? "80px auto" : "0px 15px 50px 15px"}`,
      }}
    >
      <div className="px-6 pb-8 mx-auto max-w-7xl">
        <h2 className="mb-12 text-2xl sm:text-4xl font-bold text-center text-black">
          How it works
        </h2>

        <div className={`grid ${isDesktop ? "grid-cols-3" : "grid-cols-1"} gap-8`}>
          {features.map((feature, index) => (
            <div key={index} className="flex flex-col items-start">
              <div className="flex items-center justify-center w-12 h-12 mb-6 text-white bg-black rounded-xl">
                {feature.icon}
              </div>
              <Divider style={{ width: "100%", borderColor: "black" }} />
              <div className="mt-4 space-y-2">
                <h3 className="text-xl sm:text-2xl font-bold text-black">{feature.title}</h3>
                <p className="text-sm leading-relaxed text-gray-800">{feature.description}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default HowItWorks;
