const styles = {
  container: {
    minHeight: '100vh',
    padding: '32px',
  },
  content: {
    maxWidth: '112rem',
    margin: '0 auto',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
  },
  headingContainer: {
    flexDirection: 'row',
    display: 'flex',
    justifyContent: 'center',
    textAlign: 'center',
    alignItems: 'center',
    margin: '30px 0px',
  },
  gradientHeader: {
    marginRight: '8px',
    background: 'linear-gradient(98deg, #CF0 1.63%, #EBF5C3 103.83%)',
    backgroundClip: 'text',
    color: 'transparent',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    fontFamily: 'Nohemi',
    fontSize: '40px',
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: '52px',
  },
  header: {
    color: '#FFF',
    fontFamily: 'Nohemi',
    fontSize: '40px',
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: '52px',
  },
  panel: {
    background:
      'url(/images/aiEngineBg.png), linear-gradient(180deg, #CDFF4D -52.44%, #242424 130.44%)',
    backgroundBlendMode: 'overlay',
    display: 'flex',
    flexDirection: 'row',
    borderRadius: '36px',
    padding: '14px',
    height: '100%',
  },
  imageContainer: {
    width: '55%',
    height: '100%',
    display: 'flex',
  },
  imageWrapper: {
    height: '100%',
    borderRadius: '1rem',
    overflow: 'hidden',
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  listContainer: {
    width: '45%',
    margin: '0px 15px',
  },
  button: {
    width: '100%',
    textAlign: 'left',
    padding: '16px',
    margin: '4px 0px',
    transition: 'all 0.2s',
    borderRadius: '30px',
    border: '1px solid transparent',
    backgroundColor: 'transparent',
    display: 'flex',
    alignItems: 'start',
    '&:hover': {
      backgroundColor: '#3b3b3b',
    },
  },
  selectedButton: {
    backgroundColor: '#242424',
    border: '1px solid rgba(255, 255, 255, 0.15)',
    borderRadius: '30px',
    boxShadow: '0px 10px 12px 0px rgba(0, 0, 0, 0.35)',
  },
  iconWrapper: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
  },
  selectedIconWrapper: {
    color: 'white',
  },
  title: {
    color: 'rgba(255, 255, 255, 0.90)',
    fontFamily: 'Nohemi',
    fontSize: '16px',
    fontStyle: 'normal',
    marginLeft: '10px',
    fontWeight: 600,
  },
  selectedTitle: {
    color: '#fff',
    fontFamily: 'Nohemi',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 600,
    marginLeft: '10px',
  },
  description: {
    margin: '4px 0px',
    color: 'rgba(255, 255, 255, 0.90)',
    fontFamily: 'Nohemi',
    fontSize: '14px',
    lineHeight: '24px',
    fontWeight: 400,
    fontStyle: 'normal',
  },
};

export default styles;
